theme: minima
title: github-pages-with-jekyll
author: daichi14111-home
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Added 'theme: minima' in the 1st line

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
